definitions:
  response.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  service.emailParams:
    properties:
      email:
        type: string
    type: object
  service.loginParams:
    properties:
      log_id:
        type: string
      password_encrypt:
        type: string
    type: object
  service.passwordEncryptParams:
    properties:
      password_encrypt:
        type: string
    type: object
  service.registerOrResetPasswordByEmailParams:
    properties:
      email:
        type: string
      password_encrypt:
        type: string
      validate_code:
        type: string
    type: object
  service.resetEmailParams:
    properties:
      email:
        type: string
      validate_code:
        type: string
    type: object
  service.userInfoParams:
    properties:
      age:
        type: string
      info:
        type: string
      name:
        type: string
      sex:
        type: string
      user_name:
        type: string
    type: object
host: 192.168.2.89:8082
info:
  contact:
    name: API Support
    url: http://www.swagger.io/support
  description: 接口文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: 框架接口
  version: 0.0.1
paths:
  /test:
    get:
      consumes:
      - application/json
      description: Test Swagger
      parameters:
      - description: userId
        in: path
        name: some_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 测试接口
  /user/email/reset:
    post:
      consumes:
      - application/json
      description: 重置邮箱，根据邮件中验证码
      parameters:
      - description: email,validate_code
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/service.resetEmailParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success data为null
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: token错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: 无法访问 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 内部错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: 重置邮箱
      tags:
      - 用户管理
  /user/email/reset/validate:
    post:
      consumes:
      - application/json
      description: 发送重置邮箱验证码邮件
      parameters:
      - description: email
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/service.emailParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success data为null
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: token错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: 无法访问 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 内部错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: 发送重置邮箱验证码邮件
      tags:
      - 用户管理
  /user/info:
    get:
      consumes:
      - application/json
      description: 获取用户信息
      produces:
      - application/json
      responses:
        "200":
          description: 调用成功 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: token错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: 无法访问 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 内部错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: 获取用户信息
      tags:
      - 用户管理
    post:
      consumes:
      - application/json
      description: 编辑用户信息
      parameters:
      - description: sex:0男，1女，2保密 age:年龄 user_name:用户名，昵称 name:实际姓名 info:其他信息
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/service.userInfoParams'
      produces:
      - application/json
      responses:
        "200":
          description: 调用成功 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: token错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: 无法访问 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 内部错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: 编辑用户信息
      tags:
      - 用户管理
  /user/login:
    post:
      consumes:
      - application/json
      description: 登录接口，通过email，手机号或用户名
      parameters:
      - description: log_id:email，手机号或用户名 password_encrypt:加密后的密码
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/service.loginParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success data为{\"token\":token, \"user_id\":user id}
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: token错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: 无法访问 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 内部错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
      summary: 登录
      tags:
      - 用户管理
  /user/password/reset:
    post:
      consumes:
      - application/json
      description: 重置密码（已登录状态）
      parameters:
      - description: 密码（加密过的）
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/service.passwordEncryptParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success data为null
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: token错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: 无法访问 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 内部错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: 重置密码（已登录状态）
      tags:
      - 用户管理
  /user/password/reset/email:
    post:
      consumes:
      - application/json
      description: 重置密码（发送邮件方式），根据邮件中验证码
      parameters:
      - description: email
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/service.registerOrResetPasswordByEmailParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success data为null
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: token错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: 无法访问 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 内部错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
      summary: 重置密码（发送邮件方式）
      tags:
      - 用户管理
  /user/password/reset/email/validate:
    post:
      consumes:
      - application/json
      description: 邮件发送重置密码验证码
      parameters:
      - description: 邮箱
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/service.emailParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success data为null
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: token错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: 无法访问 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 内部错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
      summary: 邮件发送重置密码验证码
      tags:
      - 用户管理
  /user/register/email:
    post:
      consumes:
      - application/json
      description: 邮件注册
      parameters:
      - description: 邮箱
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/service.registerOrResetPasswordByEmailParams'
      produces:
      - application/json
      responses:
        "200":
          description: 'Success data为{\"id": user id}'
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: token错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: 无法访问 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 内部错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
      summary: 邮件注册
      tags:
      - 用户管理
  /user/register/email/validate:
    post:
      consumes:
      - application/json
      description: 邮件发送注册验证码
      parameters:
      - description: 邮箱
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/service.emailParams'
      produces:
      - application/json
      responses:
        "200":
          description: Success data为null
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: token错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "404":
          description: 无法访问 data为null
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: 内部错误 data为null
          schema:
            $ref: '#/definitions/response.Response'
      summary: 邮件发送注册验证码
      tags:
      - 用户管理
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
