host: 127.0.0.1:9009
info:
  contact:
    name: API Support
    url: http://www.swagger.io/support
  description: 接口文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: 框架接口
  version: 0.0.1
paths:
  /test:
    get:
      consumes:
      - application/json
      description: Test Swagger
      parameters:
      - description: userId
        in: path
        name: some_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 测试接口
swagger: "2.0"
